# Generated by Django 4.0.5 on 2022-06-15 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoeSiteServerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 4, 7, 56, 445518)),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
