# Generated by Django 4.0.4 on 2022-06-18 09:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoeSiteServerApp', '0005_alter_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 18, 16, 23, 57, 969229)),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='shoeSiteServerApp.sale'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('size', 'shoe'), name='unique_migration_stock_size'),
        ),
    ]
